name: Node.js CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: cd TP3 && npm ci
      - run: cd TP3 && npm run build --if-present
      - run: cd TP3 && npm run test
