name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
      - run: npm ci --prefix /TP3
      - run: npm run build --prefix /TP3 --if-present
      - run: npm test --prefix /TP3
